apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prendaria-actualiza-bienes-liquidacion-deployment
  namespace: prendario-datos-de-referencia
  labels:
    app: app-prendaria-actualiza-bienes-liquidacion
spec:
  progressDeadlineSeconds: 60
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: app-prendaria-actualiza-bienes-liquidacion
  template:
    metadata:
      labels:
        app: app-prendaria-actualiza-bienes-liquidacion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeInfra
                operator: In
                values:
                - prendario
      tolerations:
      - key: "nodeInfra"
        operator: "Equal"
        value: "prendario"
        effect: "NoSchedule"
      containers:
      - name: app-prendaria-actualiza-bienes-liquidacion
        image: hub.donde.org.mx/dev/app-prendaria-actualiza-bienes-liquidacion:1.0.0
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "desarrollo"
        - name: ENV_SERVER_LAKIN
          valueFrom:
            secretKeyRef:
              name: app-prendaria-actualiza-bienes-liquidacion-secret
              key: ENV_SERVER_LAKIN
        - name: ENV_BASE_LAKIN
          valueFrom:
            secretKeyRef:
              name: app-prendaria-actualiza-bienes-liquidacion-secret
              key: ENV_BASE_LAKIN
        - name: ENV_USER_PRENDARIO_LAKIN
          valueFrom:
            secretKeyRef:
              name: app-prendaria-actualiza-bienes-liquidacion-secret
              key: ENV_USER_PRENDARIO_LAKIN
        - name: ENV_PASS_PRENDARIO_LAKIN
          valueFrom:
            secretKeyRef:
              name: app-prendaria-actualiza-bienes-liquidacion-secret
              key: ENV_PASS_PRENDARIO_LAKIN
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/home/node/configuraciones/private.pem"
          subPath: private.pem
          readOnly: false
          name: private-pem-storage
        - mountPath: "/home/node/logs"
          name: logs-prendario-storage
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: storecred
      volumes:
        - name: private-pem-storage
          secret:
            secretName: private-pem
            items:
            - key: private.pem
              path: private.pem
              mode: 511
        - name: logs-prendario-storage
          persistentVolumeClaim:
            claimName: logs-prendario-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
