apiVersion: v1
kind: Secret
metadata:
  name: app-prendaria-actualiza-bienes-liquidacion-secret
  namespace: prendario-datos-de-referencia
type: Opaque
stringData:
  ENV_SERVER_LAKIN: "10.10.58.98"
  ENV_BASE_LAKIN: "egYIIMHEl8+ga+S4dfU9V3M6h20qQj0cHiIEMgX7oads0yIUyHyIF3l3ZAMgMzkOwsnTut4jjsKRyQJ1rL1eu4eeOW97m3XPFpsHi64wg2MK4aC6opp27OnnHE6jwj5gHJdxFc8IF4ZqIven6fUogXTflulCZSn9ZYU8CRU6pxvyZcNGnaYSaWizWksQS51O+gzrTtIvLC9lWPIfe79wSeaSIPW15s+QpM110XbUiVGC/pyebLysMvrsfo+q1dtcBb1jlj6YzKF/tih7c3IdVWoX74+4A/mmhRo5rH8zlfO8IBHKdy2v9jJeks0KPz9qsbDK3+oefnpNmsanlKfpHA=="
  ENV_USER_PRENDARIO_LAKIN: "bZWsl2Rv+wxaUugjl+7UNkbSsuRUQ03SQftjAypDuD5WU5UWJ84Dv30BA0xUE1XtIl36yZgXTGMZAhVa624cH/AlyP/Oz1afm9iJDTdrxmx31gqhnJLv8PeS7jzljFH5fdApaUDAdXezlTLeYKaz8gNaZ4sWXy8FAqXWcuU634Po6oIZKEQHM4aXaMikxjNP+jyiSCJUFvU8JDGNXsEWSj+3Z5vMB1WSwxNJ5cQnNJLfvuPOfOG8wmcJOyelV+U9x0kqbDnig786sRlwrhCxyIuThS2TxhTaMAcCpz49wJ+Jvkou3XzR9MO61InFM4uaZARLVtCCqQgISqS/0b0RgA=="
  ENV_PASS_PRENDARIO_LAKIN: "RsBMWjWVE3fCRsO2hIbMV8/QieVMSEKCHpgiX4QOtGShu2NZlniEi1xWrdjWh87AEGzJyrNu5f/cP/0jhAS91M6ryc9IrlddeDkH+tCaI3S4GsdmAqslWpKGZJl1JvW6vHEEIS1q9uuyjhxxuODr6IuPrARScWmdlp5IyfvI7r71Ne3ox15FcYknCR455wKEkMyVJ2bqY1HDtrVk1/djfx27FSIJzDm5WY5j3EU9/8bBUz8LFvPaWz/Uv5aK1ATeJIUuyaBsP/NuvMzBheyn4OMjwNbuxyf5HD7XoV2oMa7tqzde5nhntpcPccvjODVwDDLQMeoTdLKszuf57w/etA=="
  